# This specifies on which controller (PICO board) we are running (currently 1, 2 or 3)
controller_number = 1

ENVIRONMENT_CHECK_INTERVAL = 10
PARKING_SPACE_CHECK_INTERVAL = 1
SMART_WASTE_CHECK_INTERVAL = 1
TRAFFIC_COUNT_CHECK_INTERVAL = 0.2

HEALTH_CHECK_MQTT_INTERVAL = 300

ENVIRONMENT_MQTT_INTERVAL = 30
PARKRAUM_MQTT_INTERVAL = 3
SMART_WASTE_MQTT_INTERVAL = 3

PARK_SENSOR_VERBOSITY = False
WASTE_SENSOR_VERBOSITY = False
