# This specifies on which controller (PICO board) we are running
controller_number = 1
debug = False

ENVIRONMENT_CHECK_INTERVAL = 30
PARKING_SPACE_CHECK_INTERVAL = 1.1
SMART_WASTE_CHECK_INTERVAL = 1.2
TRAFFIC_COUNT_CHECK_INTERVAL = 0.2

HEALTH_CHECK_MQTT_INTERVAL = 300

NTP_QUERY_INTERVAL = 900
NTP_TIMEOUT = 2

ENVIRONMENT_MQTT_INTERVAL = 300
PARKRAUM_MQTT_INTERVAL = 5
SMART_WASTE_MQTT_INTERVAL = 5

ENVIRONMENT_PANEL_INTERVAL = 4

NTP_TIME_VERBOSITY = False
PARK_SENSOR_VERBOSITY = False
WASTE_SENSOR_VERBOSITY = False
