@startwire

'skinparam handwritten true

'--------------------
' Waste Containers

goto(10,10)
* W1 [30x30]
move(0,-15)
* W2 [30x30]
move(0,-15)
* W3 [30x30]

goto(100,5)
* MPX3 [50x110]

W1<->MPX3 : I2C 0
W1 - MPX3 #red : 3V3
W2<->MPX3 : I2C 1
W2 - MPX3 #red : 3V3
W3<->MPX3 : I2C 2
W3 - MPX3 #red : 3V3

--

'--------------------
' Parking

goto(10,150)

* P1 [30x30]
move(0,-15)
* P2 [30x30]
move(0,-15)
* P3 [30x30]
move(0,-15)
* P4 [30x30]
move(0,-15)
* P5 [30x30]
move(0,-15)
* P6 [30x30]
move(0,-15)
* P7 [30x30]
move(0,-15)
* P8 [30x30]

goto(100,145)
* MPX1 [50x285]

P1<->MPX1 : I2C 0
P1 - MPX1 #red : 3V3
P2<->MPX1 : I2C 1
P2 - MPX1 #red : 3V3
P3<->MPX1 : I2C 2
P3 - MPX1 #red : 3V3
P4<->MPX1 : I2C 3
P4 - MPX1 #red : 3V3
P5<->MPX1 : I2C 4
P5 - MPX1 #red : 3V3
P6<->MPX1 : I2C 5
P6 - MPX1 #red : 3V3
P7<->MPX1 : I2C 5
P7 - MPX1 #red : 3V3
P8<->MPX1 : I2C 5
P8 - MPX1 #red : 3V3

--

move(50,-5)

* PICO_W [230x600]

MPX3 <-> PICO_W : I2C1
MPX1 <-> PICO_W : I2C1

MPX3 - PICO_W #red : 3V3
MPX1 - PICO_W #red : 3V3

--

move(50,-5)

* Display [100x75]

PICO_W <-> Display : I2C0

PICO_W - Display #red : 5V

* T1R [30x30]
move(0,-15)
* T1Y [30x30]
move(0,-15)
* T1G [30x30]
move(0,-15)
* T2R [30x30]
move(0,-15)
* T2Y [30x30]
move(0,-15)
* T2G [30x30]

* T3R [30x30]
move(0,-15)
* T3Y [30x30]
move(0,-15)
* T3G [30x30]
move(0,-15)
* T4R [30x30]
move(0,-15)
* T4Y [30x30]
move(0,-15)
* T4G [30x30]

--

goto (220,650)
* TC1 [30x30]
goto (260,650)
* TC2 [30x30]
goto (300,650)
* TC3 [30x30]
goto (340,650)
* TC4 [30x30]
goto (380,650)
* TC5 [30x30]
goto (420,650)
* TC6 [30x30]

@endwire
